/**
 * Solution lifecycle through the real stack (PLA-311).
 *
 * Proves: create solution from document sources, start generation, wait for
 * completion, verify part structure, rename, delete.  Exercises the full
 * solution worker pipeline through the real backend.
 */

import { test, expect } from '@playwright/test'
import { resolve } from 'node:path'
import {
  apiGet,
  apiPost,
  apiPatch,
  apiDelete,
  createClass,
  uploadDocument,
  waitForDocumentReady,
  waitForSolutionReady,
  clearTutorState,
} from './helpers'

const TEST_DATA = resolve(__dirname, 'test-data')

test.describe('Solutions (PLA-311)', () => {
  let classId: number
  let docId: number

  test.beforeAll(async () => {
    const cls = await createClass('Acceptance: Solutions')
    classId = cls.id

    const res = await uploadDocument(classId, resolve(TEST_DATA, 'sample.txt'), 'sample.txt')
    const doc = await res.json()
    docId = doc.id
    await waitForDocumentReady(docId, 30_000)
  })

  test.afterEach(async () => {
    await clearTutorState()
  })

  let solutionId: number

  test('create solution from selected sources', async () => {
    const res = await apiPost(`/api/classes/${classId}/solutions`, {
      title: 'Thermo Solutions',
      sources: [{ document_id: docId, role: 'problem_set' }],
    })
    expect(res.status).toBe(201)
    const solution = await res.json()
    solutionId = solution.id
    expect(solution.id).toBeGreaterThan(0)
  })

  test('start generation and wait for completion', async () => {
    const startRes = await apiPost(`/api/solutions/${solutionId}/start`)
    expect(startRes.ok).toBe(true)

    await waitForSolutionReady(solutionId, 60_000)

    const solutionRes = await apiGet(`/api/solutions/${solutionId}`)
    expect(solutionRes.ok).toBe(true)
    const solution = await solutionRes.json()
    expect(solution.state).toBe('ready')
    expect(solution.parts.length).toBeGreaterThan(0)
  })

  test('read individual part and verify content', async () => {
    const solutionRes = await apiGet(`/api/solutions/${solutionId}`)
    const solution = await solutionRes.json()
    const firstPart = solution.parts[0]
    expect(firstPart).toBeTruthy()
    expect(firstPart.part_id).toBeGreaterThan(0)
    // Parts have content generated by the tutor fixture
    expect(typeof firstPart.content).toBe('string')
  })

  test('rename solution', async () => {
    const renameRes = await apiPatch(`/api/solutions/${solutionId}`, {
      title: 'Renamed Solutions',
    })
    expect(renameRes.ok).toBe(true)

    const solutionRes = await apiGet(`/api/solutions/${solutionId}`)
    const solution = await solutionRes.json()
    expect(solution.title).toBe('Renamed Solutions')
  })

  test('solution appears in class list', async () => {
    const listRes = await apiGet(`/api/classes/${classId}/solutions`)
    expect(listRes.ok).toBe(true)
    const solutions = await listRes.json()
    expect(solutions.length).toBeGreaterThan(0)
    const found = solutions.find((s: { id: number }) => s.id === solutionId)
    expect(found).toBeTruthy()
    expect(found.title).toBe('Renamed Solutions')
  })

  test('delete solution removes it', async () => {
    const deleteRes = await apiDelete(`/api/solutions/${solutionId}`)
    expect(deleteRes.status).toBe(204)

    const listRes = await apiGet(`/api/classes/${classId}/solutions`)
    const solutions = await listRes.json()
    expect(solutions.find((s: { id: number }) => s.id === solutionId)).toBeUndefined()
  })

  test('solution from deleted source fails validation', async () => {
    // Upload and ingest a document, then delete it
    const res = await uploadDocument(classId, resolve(TEST_DATA, 'supplement.md'), 'supplement.md')
    const doc2 = await res.json()
    await waitForDocumentReady(doc2.id, 30_000)

    // Create solution referencing the document
    const solRes = await apiPost(`/api/classes/${classId}/solutions`, {
      title: 'Orphan Solution',
      sources: [{ document_id: doc2.id, role: 'problem_set' }],
    })
    expect(solRes.status).toBe(201)
    const sol = await solRes.json()

    // Delete the source BEFORE starting generation
    await apiDelete(`/api/documents/${doc2.id}`)

    // Start should fail or the worker should detect missing sources
    const startRes = await apiPost(`/api/solutions/${sol.id}/start`)
    if (startRes.ok) {
      // Worker should fail the solution
      const deadline = Date.now() + 30_000
      let finalState = ''
      while (Date.now() < deadline) {
        const statusRes = await apiGet(`/api/solutions/${sol.id}/status`)
        const status = await statusRes.json()
        if (status.state === 'failed' || status.state === 'cancelled' || status.state === 'ready') {
          finalState = status.state
          break
        }
        await new Promise((r) => setTimeout(r, 300))
      }
      expect(finalState).toMatch(/failed|cancelled/)
    } else {
      // Start itself rejected
      expect(startRes.status).toBeGreaterThanOrEqual(400)
    }
  })
})
